app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
logout:
    path: /logout

mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications
